export const GET_CHARACTERS = "CHARACTERS/GET_CURRENT";
export const SET_CHARACTERS = "CHARACTERS/SET_CURRENT";
export const SET_PAGE = "CHARACTERS/SET_PAGE";
export const ADD_FAVORITE = "CHARACTERS/ADD_FAVORITE";
export const REMOVE_FAVORITE = "CHARACTERS/REMOVE_FAVORITE";
export const CLEAR_FAVORITES = "CHARACTERS/CLEAR_FAVORITES";
export const SET_ERROR = "CHARACTERS/SET_ERROR";
export const SKIP_ERROR = "CHARACTERS/SKIP_ERROR";
