export const SET_QUERY = "CHARACTERS/SET_QUERY";
export const GET_CHARACTERS = "CHARACTERS/GET_CURRENT";
export const SET_CHARACTERS = "CHARACTERS/SET_CURRENT";
export const SET_ERROR = "CHARACTERS/SET_ERROR";
export const SKIP_ERROR = "CHARACTERS/SKIP_ERROR";
